"""Qualitative Meta-Grad-ECLIP figures for the paper.

Two parts:
1. Pointing-game qualitative panels (Fig 7) — load cached `meta_<image_id>.json`
   per coalition under POINTING_GAME_OUTPUT and re-render the four panels of
   the `fish_koala_balloon_laptop` example for image_ids 1 and 7.
2. dog_and_hydrant + dog_hot_dog panels (Figs 2, 8, 9) — load MetaCLIP-2 huge,
   run MetagameTokens for each (image, prompt) pair, save per-token Shapley
   maps + a combined attribution+interactions PDF under `results/<example>/`.
"""

import os
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import shapiq
import torch
from PIL import Image
from transformers import AutoImageProcessor, AutoModel, AutoProcessor

import gradeclip
import fixlip.plot
from metagame import MetagameTokens

MODEL_NAME = "facebook/metaclip-2-worldwide-huge-quickgelu"
N_IMAGE_TOKENS = 256                  # 16×16 grid

HERE = Path(__file__).resolve().parent
PATH_RESULTS = Path(os.environ.get("POINTING_GAME_OUTPUT", "results"))


# --- Part 1 — Fig 7: pointing-game qualitative panels from cached JSONs ------

GAME = "fish_koala_balloon_laptop"
IMAGE_IDS = [1, 7]
CELLS = ["fish", "fish_koala", "fish_koala_balloon", "fish_koala_balloon_laptop"]
TOP_K_PER_WORD = 10
MAX_VALUE = 0.45

# Pointing-game image dataset (one folder per game, with <i>.jpg images).
# Generated by data.py; override via POINTING_GAME_DATASET env var.
PATH_INPUT = Path(os.environ.get("POINTING_GAME_DATASET", "pointing_game")) / GAME
PATH_OUTPUT_POINTING = HERE / "results" / "pointing_game"
PATH_OUTPUT_POINTING.mkdir(parents=True, exist_ok=True)


def denormalize_std_first(img: torch.Tensor, mean, std) -> torch.Tensor:
    return img * torch.tensor(std).view(3, 1, 1) + torch.tensor(mean).view(3, 1, 1)


def render_pointing_game():
    image_processor = AutoImageProcessor.from_pretrained(MODEL_NAME)
    for image_id in IMAGE_IDS:
        pil = Image.open(PATH_INPUT / f"{image_id}.jpg")
        preprocessed = image_processor(pil, return_tensors="pt")["pixel_values"][0]
        denorm = denormalize_std_first(preprocessed, image_processor.image_mean,
                                       image_processor.image_std)
        img_np = denorm.permute(1, 2, 0).numpy().clip(0, 1)

        for cell in CELLS:
            iv = shapiq.InteractionValues.load(
                str(PATH_RESULTS / MODEL_NAME / "gradeclip" / cell
                    / f"meta_{image_id}.json")
            )
            n_words = len(cell.split("_"))
            top_k = TOP_K_PER_WORD * n_words

            result = fixlip.plot.plot_image_and_text_together(
                img=img_np,
                text=cell.split("_"),
                image_players=list(range(N_IMAGE_TOKENS)),
                iv=iv,
                plot_interactions=True,
                top_k=top_k,
                normalize_jointly=True,
                figsize=(4.5, 4.5),
                fontsize=22,
                margin=0.3,
                color_text=False,
                plot_heatmap=False,
                show=False,
                max_value=MAX_VALUE,
            )
            fig = result[0] if isinstance(result, tuple) else plt.gcf()
            for ext in ("pdf", "png"):
                out_path = PATH_OUTPUT_POINTING / f"{cell}_{image_id}.{ext}"
                fig.savefig(out_path, bbox_inches="tight", pad_inches=0.01,
                            dpi=300 if ext == "png" else None)
                print(f"  wrote {out_path}")
            plt.close(fig)


# --- Part 2 — Figs 2, 8, 9: dog_and_hydrant + dog_hot_dog from scratch -------

QUALITATIVE_EXAMPLES = [
    # (subdir,             image filename,             input text)
    ("dog_and_hydrant_1", "dog_and_hydrant_1.png", "black dog next to a yellow hydrant"),  # Fig 2
    ("dog_and_hydrant_2", "dog_and_hydrant_2.jpg", "black dog next to a green hydrant"),   # Fig 8a
    ("dog_and_hydrant_3", "dog_and_hydrant_3.jpg", "yorkshire next to a red hydrant"),     # Fig 8b
    ("dog_hot_dog",       "dog_hot_dog.png",       "a person eating a hot dog"),           # Fig 9
]


def denormalize_mean_first(img, processor):
    return img * torch.tensor(processor.image_mean).view(3, 1, 1) + torch.tensor(processor.image_std).view(3, 1, 1)


def render_qualitative():
    device = "cuda" if torch.cuda.is_available() else "cpu"
    model = AutoModel.from_pretrained(MODEL_NAME).to(device)
    model.config.vision_config._attn_implementation = "eager"
    processor = AutoProcessor.from_pretrained(MODEL_NAME)
    mode = "gradeclip"

    for subdir, img_name, input_text in QUALITATIVE_EXAMPLES:
        out_dir = HERE / "results" / subdir
        out_dir.mkdir(parents=True, exist_ok=True)
        input_image = Image.open(HERE / "images" / img_name)

        meta_explainer = MetagameTokens(model, processor, n_image_tokens=N_IMAGE_TOKENS, mode=mode)
        meta_values = meta_explainer.explain(input_image, input_text)

        image_preprocessed = processor(input_image, return_tensors="pt")["pixel_values"][0]
        input_image_denormalized = denormalize_mean_first(image_preprocessed, processor.image_processor).permute(1, 2, 0).numpy()

        for i, p in enumerate(meta_explainer.text_tokens):
            values_image = meta_explainer.second_order_explanations[i]
            gradeclip.save_explanation(
                image_preprocessed.numpy(),
                values_image,
                str(out_dir),
                f"{mode}_player_{p}",
                theta=0.4,
            )

        fig = fixlip.plot.plot_image_and_text_together(
            img=input_image_denormalized,
            text=input_text.split(" "),
            image_players=list(range(N_IMAGE_TOKENS)),
            iv=meta_values,
            plot_interactions=True,
            top_k=30,
            normalize_jointly=True,
            figsize=(5, 5),
            fontsize=22,
            margin=0.3,
            color_text=False,
            plot_heatmap=False,
            show=False,
        )
        fig.savefig(out_dir / "combined.pdf",
                    bbox_inches="tight", pad_inches=0.15)
        plt.close(fig)
        print(f"  wrote {out_dir}/combined.pdf + {len(meta_explainer.text_tokens)} explanation_*.png")


def main() -> None:
    render_pointing_game()
    render_qualitative()


if __name__ == "__main__":
    main()
