import os
import subprocess

HERE = os.path.dirname(os.path.abspath(__file__))

GAMES = [
    ['plane', 'balloon', 'jeep', 'pizza'],
    ['church', 'jeep', 'lemon', 'fish'],
    ['lemon', 'pizza', 'fish', 'balloon'],
    # ['fish', 'koala', 'balloon', 'laptop'],
    # ['koala', 'plane', 'church', 'lemon'],
    # ['balloon', 'church', 'laptop', 'acorn'],
    # ['jeep', 'laptop', 'pizza', 'koala'],
    # ['laptop', 'lemon', 'acorn', 'plane'],
    # ['pizza', 'acorn', 'koala', 'church'],
    # ['acorn', 'fish', 'plane', 'jeep']
]
# Output directory for the sweep. Override with POINTING_GAME_OUTPUT env var.
PATH_OUTPUT = os.environ.get("POINTING_GAME_OUTPUT", os.path.join(HERE, "results"))
# Input dataset root. Each game's images live at <DATASET_ROOT>/<game>/<i>.jpg.
# Generated by data.py; override via POINTING_GAME_DATASET env var.
DATASET_ROOT = os.environ.get("POINTING_GAME_DATASET", "pointing_game")
RANDOM_STATE = 0
BUDGET = 2**17

for game in GAMES:
    PATH_INPUT = os.path.join(DATASET_ROOT, "_".join(game))
    for model_name, batch_size in {
        # "openai/clip-vit-base-patch16": 2048, # 3 min per iter / 4h
        # "google/siglip2-base-patch32-256": 4096, # 3 min per iter / 4h
        # "google/siglip2-large-patch16-256": 2048, # 7 min per iter / 7h
        "facebook/metaclip-2-worldwide-huge-quickgelu": 1024 # 9 min per iter / 9h
    }.items():
        for i in range(1, 5):
            class_labels = game[:i]
            cl = "_".join(class_labels)
            subprocess.run([
                "sbatch",
                "run_pointing_game_fixlip.sh",
                model_name,
                PATH_INPUT,
                os.path.join(PATH_OUTPUT, model_name, "fixlip", cl),
                cl,
                str(BUDGET),
                str(batch_size),
                str(RANDOM_STATE)
            ])